### ISSUE TITLE
Missing "response example" in download PDF invoice REST API documentation

### ISSUE THREAD

**Issue by walterdolce** [aiven/aiven-client#136]
I am currently implementing the ability to download an invoice PDF (expect PR soon!) but I noticed the download PDF invoice REST API endpoint is not documented in detail ([link](https://api.aiven.io/doc/#api-Project_Billing-ProjectInvoiceGet)).

The `Response Example` present in other REST API endpoints is missing. Is this expected?

Thank you

**Comment by ojarva** [comment]
Hi,

This endpoint returns PDF file as-is without any wrapping, and our current API documents generation do not support generating that as an example (i.e., we generate response examples from schemas, and there's no easy way to put something like "Response example: this endpoint responds with a raw PDF file" to there).

I hope this answers your question; please reopen this issue if you have further questions or issues regarding this endpoint.

Eagerly waiting for your PR :)

**Comment by walterdolce** [comment]
@ojarva #137 is ready for review! :)
