### ISSUE TITLE
Add examples for tagging projects and services

### ISSUE THREAD

**Issue by lornajane** [aiven/aiven-client#231]
# What can we help you with?

I'd love to see some examples of #228 in action and which objects I can tag.

# Where would you expect to find this information?

Either in the README of this project, or with the other docs https://developer.aiven.io/docs/tools/cli

**Comment by rominf** [comment]
It looks like examples were added here: [Tag your Aiven resources (developer portal)](https://developer.aiven.io/docs/platform/howto/tag-resources.html#tag-your-aiven-resources). Should I close this issue?

**Comment by lornajane** [comment]
Thanks for spotting and updating the issue! I'll close.
