### ISSUE TITLE
argx should preserve signature of wrapped function

### ISSUE THREAD

**Issue by aiven-amartin** [aiven/aiven-client#268]
In https://github.com/aiven/aiven-client/blob/46f2cfd7c674fdfb62e277ede33fd77283f9292a/aiven/client/argx.py#L88, we don't cast back to the signature of the wrapped function, but we should, as well as appending the type of the added args.

See https://mypy.readthedocs.io/en/stable/generics.html#declaring-decorators.

**Comment by NotoriousPyro** [comment]
`def wrap(func)` should also ideally have [@functools.wraps](https://docs.python.org/3/library/functools.html#functools.wraps)

**Comment by rominf** [comment]
#322 is the fix.
