### ISSUE TITLE
Change default to `--no-project-vpc` when creating a service

### ISSUE THREAD

**Issue by TibsAtWork** [aiven/aiven-client#290]
# What is currently missing?

When I create a service using the console, it defaults to "Public Internet".

When I create a service using `avn`, it defaults to using a VPC is there is one available. For instance I observed this with:
```
avn project switch <project>
avn service create tibs-demo-pg --service-type pg --cloud google-europe-north1 --plan hobbyist
```

When I then try to connect to the service CLI:
```
avn service cli tibs-demo-pg
```
I get:
```
psql: error: could not translate host name "tibs-demo-pg-dev-sandbox.aivencloud.com" to address: nodename nor servname provided, or not known
```
(and the same result if I use `psql` directly).

This was entirely surprising to me, as I'd expect the console and CLI to behave the same way when creating a service.

I can work around this by knowing what the problem is, and then migrating the service.
For reference of anyone reading this, that means:

1. Go to the *Cloud and VPC* section on the service page on the console
2. Check that it says "Project VPC"
3. Select *Migrate Cloud*
4. Choose a service from the appropriate tab (for instance, `Europe`) instead of the `VPC` tab
5. Migrate

# How could this be improved?

Change the default behaviour to pass `project_vpc_id: null`, as if the user had specified `--no-project-vpc`.

This is an incompatible change, so would need to be called out in the release notes.

# Is this a feature you would work on yourself?

[x] I plan to open a pull request for this feature

**Comment by rikonen** [comment]
I wonder if a safer change would be to make service creation check whether the project has VPCs, and if it does, fail the operation unless either `--no-project-vpc` or `--project-vpc-id <vpc_id>` switch is given? Defaulting to either mode of operation is potentially unsafe / unexpected when there are VPCs in the project.

**Comment by TibsAtWork** [comment]
I can see that point. I assume creating/deleting a VPC is a rare occurrence? (otherwise I'd worry about the race condition between asking if there's a VPC and doing the creation/update)

I see from `avn vpc list` that quite a few clouds have VPCs, so its quite possible for a user to come across this.

It does feel a little wrong to have to do a query before a create/update, but that's perhaps not an issue.

It is a bit horrible to tell the user "I shan't do that because of this thing you've never heard of, try again with `--no-project-vpc` or `--project-vpc-id <vpc_id>`" - the error message would need some work to make it friendly.

**Comment by rikonen** [comment]
Not sure how unfamiliar concept VPCs are for people working with projects that have those since shared test projects may not be common in general. Average cli users might have created the VPCs themselves when they exist or are well aware of those.

Changing the behavior so that VPCs are by default not used would also have security implications since if anyone assumes the cli works like it used to work and that service is in a VPC and not exposed into public internet, there could be big problems when it later on turns out the service in fact was publicly accessible (even if password protected, obviously).

**Comment by TibsAtWork** [comment]
The more I think about it, the more your points seem good to me.
I don't particularly want to have to explain VPCs to people when talking about simple use of `avn`, but equally we shouldn't be removing the capabilities for expert users who are already using the tool. And your point about potential security surprises is a good one.

I've also been uncomfortable with introducing a new switch, just to get back to the old default behaviour. It makes the code inside `avn` more complicated for little benefit.

I'll have a look at how to implement this alternate approach.
