### ISSUE TITLE
Help text for USER_CONFIG is misleading

### ISSUE THREAD

**Issue by kbrownlees** [aiven/aiven-client#30]
In the help text for 'avn service update' it has:

> -c USER_CONFIG        User configuration: KEY=JSON_VALUE

This is fairly misleading since for arrays it actually takes a comma separated string (https://github.com/aiven/aiven-client/blob/master/aiven/client/cli.py#L33).

Also, probably would hurt to have an example of updating the ip whitelist in the docs (for postgres)?

> avn service update my_service -c ip_filter='10.0.0.1/24,10.0.0.2/24'

**Comment by melor** [comment]
I updated both the command-line option help text and README by adding an `ip_filter` example. Thank you for the feedback!
