### ISSUE TITLE
cli: add support for deleting pending invites : when a new release

### ISSUE THREAD

**Issue by ademar59** [aiven/aiven-client#314]
# What can we help you with?

this PR is merged https://github.com/aiven/aiven-client/pull/312

when a new release of aiven cli (nothing since 1rst of July)

# Where would you expect to find this information?

**Comment by hnousiainen** [comment]
Thanks for asking, we've now released 2.17.0 which contains the PR you mentioned. The release is at https://github.com/aiven/aiven-client/releases/tag/2.17.0 and also published on PyPI.
