### ISSUE TITLE
API Deprecated

### ISSUE THREAD

**Issue by brunodomenici** [aiven/aiven-client#60]
Hi,

I'm trying to retrieve logs:

```
avn logs --project <project>
ERROR	command failed: Error: {"errors":[{"message":"API deprecated, switch to /project/<project>/service/<service_name>/logs endpoint","status":400}],"message":"API deprecated, switch to /project/<project>/service/<service_name>/logs endpoint"}

```

Thank you

**Comment by ojarva** [comment]
Hi,
Please update your `aiven-client` to the newest version - we greatly improved our log view (https://aiven.io/blog/want-greater-command-over-your-service-logs/), and the old endpoint was deprecated, as it is not compatible with the new functionality, without breaking changes.

**Comment by ojarva** [comment]
I'll close this issue for now - if you encounter the same problem with new `aiven-client` version, please reopen and we can dig deeper into why this is happening.
