### ISSUE TITLE
Logs API deprecated

### ISSUE THREAD

**Issue by galindro** [aiven/aiven-client#62]
After successfully logged, the bellow error is showed when I try to read logs from our project:

```bash
$ avn logs -f prod
ERROR	command failed: Error: {"errors":[{"message":"API deprecated, switch to /project/<project>/service/<service_name>/logs endpoint","status":400}],"message":"API deprecated, switch to /project/<project>/service/<service_name>/logs endpoint"}
```

Version:  aiven-client (2.1.3-8-g76a0b5d)

**Comment by ojarva** [comment]
This is a bit confusing and something we need to address. For fetching service logs, you can use `avn service logs -f prod` command - `avn logs` uses older, slower endpoint, which is not available for services created (or updated, or started) after mid-May 2018.

**Comment by galindro** [comment]
Worked @ojarva . Tks

**Comment by ojarva** [comment]
Great! I'll keep this issue open, as this should be improved in general to make it easier to use. We'll close this when changes go in to master branch.

**Comment by rominf** [comment]
I assume there is no reason to keep this ticket open anymore. Feel free to open a new ticket if you have any (related) problems.
