### ISSUE TITLE
`avn service logs` doesn't allow pagination

### ISSUE THREAD

**Issue by henrytk** [aiven/aiven-client#63]
I ran `avn service logs --project project-name service-name` expecting to get a lot of logs. It did not go far back enough so I had to work out how to paginate/offset the returned values.

I can see I can set `-n` (limit) to up to 500 according to [the documentation](https://api.aiven.io/doc/#api-Project-ProjectGetServiceLogs), but that doesn't go far back enough. The documentation indicates an offset can be passed, which I expect is the mechanism for searching back through log history, but the aiven-client does not expose this configuration.

Can you add an `-o` (offset) flag, or some other way of allowing iteration through log history? Thanks.

Also, as a bonus, as a user I really don't care what an offset is, or what the internal organisation of the logs is, I just want to see logs in chronological order (ascending or descending).

**Comment by Ormod** [comment]
Hi, you want to use the -f/--follow flag, it'll take care of this automatically for you.

**Comment by henrytk** [comment]
@Ormod thanks.

I tried using `-f`: it outputted on 'page', then threw this error:

```
ERROR	command failed: ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```

**Comment by Ormod** [comment]
So what was the actual command line you used? 

avn service logs -f --desc --project project-name service-name ?

**Comment by henrytk** [comment]
I'm closing this issue now. Combining `-f` with `-S desc` achieved what I wanted. Thank you.

On a related note, the mechanism for paging via the API really isn't very intuitive for a couple of reasons:

1. It's not clear where offsets start _before_ you start sending API requests.
1. It seems to be a `POST` request for [getting service logs](https://api.aiven.io/doc/#api-Project-ProjectGetServiceLogs). This is semantically invalid; it is perfectly legitimate to send the data required (limit, offset, sort order) in the body of a `GET` request.

Don't let the nagging fool you, I love Aiven :)
