### ISSUE TITLE
avn logout fails on Mac OSX

### ISSUE THREAD

**Issue by Jammink2** [aiven/aiven-client#89]
Tried
```
$  avn user logout 
```
and got

```
ERROR	command failed: Error: 404: Not Found
```

**Comment by Jammink2** [comment]
Note:  Works just fine on Fedora; is failing on Mac OSX 10.12.6

**Comment by melor** [comment]
Was fixed by upgrading to the latest aiven-client version, closing.

**Comment by Jammink2** [comment]
Was old version of avn client.  Fixed with latest.
