### ISSUE TITLE
'pg' is the only service type with a shortnened name

### ISSUE THREAD

**Issue by Jammink2** [aiven/aiven-client#91]
More of a ''nice to have"" feature.

When  you run
```
$  avn service types

```

``` pg ``` is the only service with a shorthand variant.

For the sake of consistency/and or command-line brevity, could each of these other services have a shorthand variant?  Instinctively, I typed in ```es``` when creating an Elasticsearch service.

**Comment by melor** [comment]
The service type name is "pg" for historical reasons and we won't be changing that.
