### ISSUE TITLE
simple counter for 'avn events' (and other discrete outputs)

### ISSUE THREAD

**Issue by Jammink2** [aiven/aiven-client#92]
```avn events`` returns basically an event log.  

I can imagine an admin possibly wanting an easy, built-in function that counts the numbers of events by user.

Here's the clumsy way I currently do this:

```
avn events > events && wc -l events
     102 events
```

**Comment by melor** [comment]
This can be implemented outside the aiven-client, like in your example. The other option is to interface directly with the python client library and do the processing in Python. The given example is just a single specific use case and there are tons more of them and we won't be trying to address all of those in aiven-client.
